### ISSUE TITLE
Rule missing for implementation of testCase.force

### ISSUE THREAD

**Issue by DamienCassou** [foretagsplatsen/ftgp-eslint#19]
A rule is needed to make sure we don't commit

```js
testcase.subclass((that, my) => {
    my.force = function() {
        return true;
    };
}
```

This is the equivalent of `fdescribe` and `fit` which we forbid already in https://github.com/foretagsplatsen/eslint-config-ftgp.

**Comment by BenjaminVanRyseghem** [comment]
yep.

But we wanted to have migrated all the tests before (as know we have 3 ways of writing a test class...)

**Comment by DamienCassou** [comment]
Why do you want to migrate all tests before forbidding `my.force`? I have the impression the 2 can be done in any order.

**Comment by BenjaminVanRyseghem** [comment]
Either we implement the rule so that it covers the 2 ways of forcing tests, or we wait till the migration is done

**Comment by DamienCassou** [comment]
Benjamin Van Ryseghem <notifications@github.com> writes:
> Either we implement the rule so that it covers the 2 ways of forcing
> tests, or we wait till the migration is done

do you mean we should duplicate
https://github.com/tlvince/eslint-plugin-jasmine/blob/master/docs/rules/no-focused-tests.md
?

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by DamienCassou** [comment]
closing as the project is being archived
