### ISSUE TITLE
How to run the tests

### ISSUE THREAD

**Issue by DamienCassou** [foretagsplatsen/ftgp-eslint#7]
I see some tests in `tests/`, but don't know how to run them. Can you please add a "Contribution" section to the readme or give me the necessary info so that I write one myself?

Thanks

**Comment by DamienCassou** [comment]
I found that in `package.json`:

```
mocha tests/lib/**/*.js --reporter progress
```

If that's the right way, can I add a `run-tests.sh` as the root of the repository and reference that in both `package.json` and `.travis.yml`?

**Comment by BenjaminVanRyseghem** [comment]
you don't need a `.sh` file.

just run `npm test`.

This is a very common practice (actually that the default task travis is running on every project).

**Comment by DamienCassou** [comment]
Thanks
